### ISSUE TITLE
animation is blurry

### ISSUE THREAD

**Issue by PembaTamang** [PatilShreyas/MaterialDialog-Android#1]
The animation is blurry do I need to provide a scaletype?

**Comment by PatilShreyas** [comment]
Which animation you implemented?

**Comment by PatilShreyas** [comment]
@PembaTamang Sorry for the too much late reply. What's happening Actually can you please describe?

**Comment by PatilShreyas** [comment]
@PembaTamang If you are using animation which is small in scale you can obtain `AnimationView` from instance and set scale as you want

**Comment by PatilShreyas** [comment]
Due to inactivity, I'm closing this issue. Feel free to re-open it if you have a proper description.

**Comment by PembaTamang** [comment]
sorry for not replying but I am not using the library anymore. I will let you know if I use it again.
Sorry once again
