### ISSUE TITLE
[FEATURE REQUEST] Create dialog with a simple drawable image instead of animation

### ISSUE THREAD

**Issue by bxscikai** [PatilShreyas/MaterialDialog-Android#13]
This library is exactly what I'm looking for except I just need a simple image in place of the animation, it would be nice if the library can let me set a drawable image instead of an animation.

**Comment by PatilShreyas** [comment]
Hello @bxscikai. Your request seems interesting. But problem is images have wide dimensions. By using images instead of animations may lose quality of dialog or they will not seem interesting.
