### ISSUE TITLE
Keeps crashing on Android7.0

### ISSUE THREAD

**Issue by mf-mindcrewtech** [PatilShreyas/MaterialDialog-Android#14]
On Nougat, it was keep crashing with .setAnimation("delete_anim.json") method and there is not a single Log, can you please test

**Comment by PatilShreyas** [comment]
Hi @mf-mindcrewtech, can you provide your implemention?

**Comment by mf-mindcrewtech** [comment]
private BottomSheetMaterialDialog mAnimatedBottomSheetDialog;

private void showDelete(){

        try {
            mAnimatedBottomSheetDialog = new BottomSheetMaterialDialog.Builder(this)
                    .setTitle("Delete?")
                    .setMessage("Are you sure want to delete this profile?")
                    .setCancelable(false)
                    .setPositiveButton("Delete", R.drawable.ic_delete, new BottomSheetMaterialDialog.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialogInterface, int i) {
                            Constant.showErrorToast("Deleted!",getApplicationContext());
                            dialogInterface.dismiss();
                        }
                    })
                    .setNegativeButton("Cancel", R.drawable.ic_close, new BottomSheetMaterialDialog.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialogInterface, int which) {
                            Constant.showErrorToast("Cancelled!",getApplicationContext());
                            dialogInterface.dismiss();
                        }
                    })
                    .setAnimation("delete_anim.json")
                    .build();
            mAnimatedBottomSheetDialog.show();
        }catch (Exception e){
            e.printStackTrace();
        }

    }

**Comment by mf-mindcrewtech** [comment]
@PatilShreyas please check and let me know if there is any error

**Comment by mf-mindcrewtech** [comment]
If I comment .setAnimation("delete_anim.json") method, it works fine on Andorid7, is there a min sdk thing?

**Comment by PatilShreyas** [comment]
@mf-mindcrewtech There's no minSdk like thing here. For testing purpose try moving your file from assets to raw folder in `res` and load file from `raw` folder using `R.raw.delete_anim`.

See if it runs or gives problem and let me know. Then we'll do further actions.

**Comment by PatilShreyas** [comment]
Any updates @mf-mindcrewtech ?

**Comment by mf-mindcrewtech** [comment]
Hi @PatilShreyas still crashing R.raw.delete_anim in Android7.0, can you please check BTW No logs have been generated (My code is also in try/catch but no exception there)

**Comment by PatilShreyas** [comment]
Okay @mf-mindcrewtech. I'll look into it.

**Comment by PatilShreyas** [comment]
@mf-mindcrewtech For testing purpose, I'll need your implemention to reproduce error. Can you please provide your implemention on GitHub or simply send me your project zip on mail: shreyaspatil125@gmail.com

**Comment by mf-mindcrewtech** [comment]
@PatilShreyas I used your library in my running project, so can't share the complete code, But i'll send you the method which i am using

private void showDelete(){
BottomSheetMaterialDialog mAnimatedBottomSheetDialog;
        try {
            mAnimatedBottomSheetDialog = new BottomSheetMaterialDialog.Builder(this)
                    .setTitle("Delete?")
                    .setMessage("Are you sure want to delete this profile?")
                    .setCancelable(false)
                    .setPositiveButton("Delete", R.drawable.ic_delete, new BottomSheetMaterialDialog.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialogInterface, int i) {
                            Constant.showErrorToast("Deleted!",getApplicationContext());
                            dialogInterface.dismiss();
                        }
                    })
                    .setNegativeButton("Cancel", R.drawable.ic_close, new BottomSheetMaterialDialog.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialogInterface, int which) {
                            Constant.showErrorToast("Cancelled!",getApplicationContext());
                            dialogInterface.dismiss();
                        }
                    })
                    .setAnimation("delete_anim.json")
                    .build();
            mAnimatedBottomSheetDialog.show();
        }catch (Exception e){
            e.printStackTrace();
        }
    }

**Comment by PatilShreyas** [comment]
Okay. Thanks!

**Comment by PatilShreyas** [comment]
@mf-mindcrewtech I tried it on my device (Android 7.0 API 24) with Animation. I found that it's running fine without any errors.

**Comment by mf-mindcrewtech** [comment]
@PatilShreyas okay but still crashing for me :(

**Comment by PatilShreyas** [comment]
@mf-mindcrewtech Have you included Lottie library as dependency in project?

I'll suggest you to clone this repo and import sample app of this project in your Android studio and run app in your device and test if same error occurs or not.

**Comment by mf-mindcrewtech** [comment]
@PatilShreyas I got the issue, which is with the delete_anim.json (I downloaded another one from lottie). I replaced with your one and it works. Thanks for kind help

**Comment by PatilShreyas** [comment]
Okay @mf-mindcrewtech and thanks for the clarification!

**Comment by PatilShreyas** [comment]
As problem is solved now, can we close this issue?

**Comment by mf-mindcrewtech** [comment]
Yupp please close it

**Comment by PatilShreyas** [comment]
Thanks for using this library.😀
