### ISSUE TITLE
Align button on center while having one button

### ISSUE THREAD

**Issue by arifix** [PatilShreyas/MaterialDialog-Android#15]
When I'm using one button(PositiveButton), that is aligned on right. Is it possible to center align it?

Thanks in advance :)

**Comment by PatilShreyas** [comment]
Thanks @arifix for this suggestion. But it doesn't looks nice after having button in center. As Android's `AlertDialog` shows buttons on its positions, this library also does the same.

**Comment by arifix** [comment]
Thanks for your quick reply & explanation.
Also thanks again for creating this beautiful library :)

**Comment by PatilShreyas** [comment]
Thank you!
