### ISSUE TITLE
[BUG] Positive/Negative button icon size

### ISSUE THREAD

**Issue by itsaxay** [PatilShreyas/MaterialDialog-Android#16]
-- Thank you for awesome libraries --

Buttons icon size issue
![Screenshot_20191204-184605](https://user-images.githubusercontent.com/10158212/70145607-88a3e700-16c6-11ea-8cf4-03ab5765ccf7.jpg)

**Comment by PatilShreyas** [comment]
Hi @itsaxay. Thanks for reporting this. But maybe that icon is larger in size. Try to keep it's pixel low (for e.g. 24dp)

**Comment by itsaxay** [comment]
yes i fixed with 24dp size. but is it possible to change size with lib?

**Comment by PatilShreyas** [comment]
No. It's not. Because different devices has different screen sizes. It'll not perform good in such cases. As your issue is solved now, can we close it?
