### ISSUE TITLE
How can I change the text color/size of the title and message of the dialog?

### ISSUE THREAD

**Issue by Rujen1719** [PatilShreyas/MaterialDialog-Android#17]

**Comment by PatilShreyas** [comment]
Hi @Rujen1719. I'm Working on that and it'll be available in next release.

**Comment by PatilShreyas** [comment]
This feature has been implemented in `v2.0`. See docs for more information.
Due to some problems, the size of text can't be changed but color styling is possible.
Thank you!

**Comment by Rujen1719** [comment]
Thank you very much!
