### ISSUE TITLE
This component requires that you specify a valid TextAppearance attribute.

### ISSUE THREAD

**Issue by DiMiTriFrog** [PatilShreyas/MaterialDialog-Android#21]
I had an error when I tried to run the project.

The error:

`Caused by: java.lang.IllegalArgumentException: This component requires that you specify a valid TextAppearance attribute. Update your app theme to inherit from Theme.MaterialComponents (or a descendant).`

My styles.xml 

<resources>

    
    <style name="AppTheme" parent="Theme.MaterialComponents.Light">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:fontFamily">@font/montserrat</item>

        
        <item name="material_dialog_background">#FFFFFF</item>
        <item name="material_dialog_title_text_color">#000000</item>
        <item name="material_dialog_message_text_color">#5F5F5F</item>
        <item name="material_dialog_positive_button_color">@color/colorAccent</item>
        <item name="material_dialog_positive_button_text_color">#FFFFFF</item>
        <item name="material_dialog_negative_button_text_color">@color/colorAccent</item>
    </style>

</resources>

**Comment by PatilShreyas** [comment]
Hi, have you set that theme from manifest?

**Comment by DiMiTriFrog** [comment]
> Hi, have you set that theme from manifest?
I didn't know I had to make this change. Everything works fine!

Now my styles.xml ->
    
    <style name="AppTheme" parent="Theme.MaterialComponents.Light.NoActionBar.Bridge">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

    </style>

and in my AndroidManifest.xml ->
`android:theme="@style/Theme.MaterialComponents.Light.NoActionBar.Bridge"` 

Thank you!
