### ISSUE TITLE
Dialog dissappers after orientation changes.

### ISSUE THREAD

**Issue by isabsent** [PatilShreyas/MaterialDialog-Android#24]
You have to use `DialogFragment` as a base class for your dialogs to avoid this problem.

**Comment by PatilShreyas** [comment]
Thanks @isabsent for this. I'll try to figure it out.

**Comment by isabsent** [comment]
public class RotationSafeDialog extends DialogFragment {
        private String message;
        private Activity act;
    
        @TargetApi(Build.VERSION_CODES.M)
        @Override
        public void onAttach(Context context) {
            super.onAttach(context);
    
            try {
                act = (FileManagerActivity) context;
            } catch (ClassCastException castException) {
    
            }
        }
    
        @SuppressWarnings("deprecation")
        @Override
        public void onAttach(Activity activity) {
            super.onAttach(activity);
    
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
                try {
                    act = (FileManagerActivity) activity;
                } catch (ClassCastException castException) {
    
                }
            }
        }
    
        @Override
        public void onDetach() {
            super.onDetach();
            act = null;
        }
    
        @Override
        public void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            message = getArguments().getString(IntentConstants.EXTRA_MESSAGE);
        }
    
        @Override
        public Dialog onCreateDialog(Bundle savedInstanceState) {
            AlertDialog dialog = new AlertDialog.Builder(getActivity())
                    .setTitle(getString(R.string.cloud_connection))
                    .setMessage(message)
                    .setNegativeButton(android.R.string.no, null)
                    .setPositiveButton(android.R.string.yes, new DialogInterface.OnClickListener() {
    
                                @Override
                                public void onClick(DialogInterface dialog, int which) {
    
                                }
                            }
                    )
                    .create();
            return dialog;
        }
    }

**Comment by PatilShreyas** [comment]
This should be managed from the `Activity` side I think. Whoever is creating dialog that should take care of that.

**Comment by isabsent** [comment]
My code above is the way to take care about it.

**Comment by PatilShreyas** [comment]
Yes. I liked your suggestion. Will try to release next version with this.
