### ISSUE TITLE
Build failed[BUG/FEATURE REQUEST] TITLE HERE

### ISSUE THREAD

**Issue by omkarghurye1998** [PatilShreyas/MaterialDialog-Android#26]
Write information about Bug/Feature Request here
The project is running fine when i remove the implementation 'com.airbnb.android:lottie:3.3.6' from the gradle

The error is caused due to implementation 'com.airbnb.android:lottie:3.3.6' 
https://stackoverflow.com/q/61660305/13472560

**Comment by PatilShreyas** [comment]
Connect to the intenet and try syncing project with gradle files.

**Comment by PatilShreyas** [comment]
Since the issue isn't clarified I'm closing this. Feel free to reopen if you want to discuss further.
