### ISSUE TITLE
add edittext

### ISSUE THREAD

**Issue by cleawrence** [PatilShreyas/MaterialDialog-Android#27]
Write information about Bug/Feature Request here
Hi is it possible to add an editext to materialdialog ?

thanks.

**Comment by PatilShreyas** [comment]
This library only shows the informative material dialog with animation. So it's not possible to support complex views like EditText and any other. So it's not recommended. Thanks for thinking about this.

**Comment by TheRedSpy15** [comment]
I feel this could be really useful. It would make it easier to make a dialog for getting user input, that matches the other (Material)dialogs in an app visually speaking
