### ISSUE TITLE
[BUG/FEATURE REQUEST] Lottie very big

### ISSUE THREAD

**Issue by P4drote** [PatilShreyas/MaterialDialog-Android#28]
When choosing a very large lottie, it looks disproportionate in the dialogue.

It can be solved by changing the property in the xml of the lottie:

android: scaleType = "centerCrop"
by
android: scaleType = "centerInside"

**Comment by PatilShreyas** [comment]
Hi @P4drote, it's not recommended to set `scaleType` for all animations. If you want to customize it you can do it. Just get `AnimationView` using calling `getAnimationView()` on material dialog instance and you can set scale after this.
