### ISSUE TITLE
Migrate project to Kotlin

### ISSUE THREAD

**Issue by kingahmedino** [PatilShreyas/MaterialDialog-Android#34]
I would like to contribute to this project by helping to migrate all existing Java code to Kotlin

**Comment by PatilShreyas** [comment]
Thanks @kingahmedino for your thought on contributing to this project. Migration of this library to the Kotlin is already WIP. See https://github.com/PatilShreyas/MaterialDialog-Android/pull/33

**Comment by PatilShreyas** [comment]
Duplicate of #32. You can refer this issue and PR #33
