### ISSUE TITLE
Support for HTML text in message

### ISSUE THREAD

**Issue by yustapps** [PatilShreyas/MaterialDialog-Android#35]
Hi,

is there a way to use html text, i want for example this text:

Hi, my name is **John**.
But I want John to be bold text.

Can I do this ? I tried with strings file "<b>" but not.

**Comment by yustapps** [comment]
Can you help me?

**Comment by PatilShreyas** [comment]
@yustapps currently it's not available in this library. But we can make it possible by exposing TextView of dialog. Need to plan for it

**Comment by yustapps** [comment]
Thank you, alert me when it will done. I will use it.

**Comment by PatilShreyas** [comment]
I can't say that it'll be implemented or not since it's not an important requirement for showing in a dialog. Basically title should be bold in dialog and body shouldn't be bold. So I guess we shouldn't do that in Material Dialog.

**Comment by yustapps** [comment]
But can be useful when you want to mark some text, like ... Do you want to remove "X"?

**Comment by PatilShreyas** [comment]
Thanks, @yustapps for this issue. This issue has been fixed and implemented in the new version `2.2.1`.
