### ISSUE TITLE
Button Color is different setted in style.xml

### ISSUE THREAD

**Issue by hwaniRed** [PatilShreyas/MaterialDialog-Android#37]
I use theme that used in sample project
and color change colorPrimary, colorPrimaryDark. colorAccent to my style

but totally different color is shown to Application
that color be found anywhere of project.

please help me,

**Comment by PatilShreyas** [comment]
Maybe you haven't set that theme from manifest XML.

**Comment by PatilShreyas** [comment]
Closing this issue. Feel free to discuss if you need some help.
