### ISSUE TITLE
NETWORK PERMISSION

### ISSUE THREAD

**Issue by skedaddl3** [PatilShreyas/MaterialDialog-Android#39]
After adding 3 implementations in my Gradle network permission is missing.
NetworkInfo activeNetworkInfo = connMgr.getActiveNetworkInfo();

**Comment by PatilShreyas** [comment]
@skedaddl3 what you need exactly? May I help?

**Comment by skedaddl3** [comment]
@PatilShreyas I'm using some deprecated libraries maybe that's the issue, that's why when i tried to implement your MaterialDialog in my project I get error like missing some Network Permission.

**Comment by PatilShreyas** [comment]
Okay. Then it's not related with this library. Closing it.
