### ISSUE TITLE
[FEATURE REQUEST] Message text not centered

### ISSUE THREAD

**Issue by fmeneuhe** [PatilShreyas/MaterialDialog-Android#42]
Hi,
Now the dialog message text is forced to be aligned centred. It would be nice to choose the alignment (left, right,...). 
Or at least by default left and not center. 
Thanks

**Comment by PatilShreyas** [comment]
This seems a good feature request. Will work on it.

**Comment by PatilShreyas** [comment]
Thanks, @fmeneuhe for this issue. This issue has been fixed and implemented in the new version `2.2.1`.
