### ISSUE TITLE
[BUG] Button not accessible on small screens

### ISSUE THREAD

**Issue by Awsom3D** [PatilShreyas/MaterialDialog-Android#44]
Hi, thanks for your work on this lib, it's super useful !

Unfortunately, some of my users are complaining that they can't click on the dialog button because it's simply out of the window, in portrait or paysage. 
I found out that they have relatively small screens (720p or less).

On my larger smartphone, the animation is effectively disabled in paysage to make some more room, but on smaller phones it doesn't work either way.

Is there a way to fix this properly in the lib so users can scroll to the dialog button ?

Thanks for your input,

**Comment by Awsom3D** [comment]
In case anyone need it, here is my hotfix in kotlin, everytime I build a materialDialog.
```kotlin
        if (resources.configuration.screenLayout and Configuration.SCREENLAYOUT_SIZE_MASK == Configuration.SCREENLAYOUT_SIZE_SMALL) // Remove animation part for small screen
            materialDialog.animationView.visibility = View.GONE
```
But it's not a long term solution since users won't be able to scroll if the text gets longer.

**Comment by PatilShreyas** [comment]
Thanks @Awsom3D for reporting this issue. Will fix this issue

**Comment by PatilShreyas** [comment]
@Awsom3D I tested this on the device (emulator) having dimension ***3.5"*** and saw that it's perfectly working fine. Can you give me more details on this?

**Comment by PatilShreyas** [comment]
@Awsom3D Also, a small recording/snapshot of the issue would be useful.

**Comment by Awsom3D** [comment]
I think the main difference is that I have a few lines of text (about 7), so my modal may be longer than yours.

What you see below is the version I have hotfix'ed, but you can try the same on your device and see that the behavior will be different, and you won't be able to see the button anymore.

Some of my users have very small screens 😅

![Screenshot_20210423-100254](https://user-images.githubusercontent.com/1741288/115840568-1eefbe80-a41c-11eb-8135-cfe54edd560e.jpg)

https://user-images.githubusercontent.com/1741288/115840639-2dd67100-a41c-11eb-8a21-742da16636af.mp4

**Comment by PatilShreyas** [comment]
@Awsom3D Thanks for sharing these references. Now I got the problem. 

So you're using this as an informative dialog. I think instead of hiding animation for smaller screens, we should support ***Scroll-ability*** for the dialog. I'll take a look at it.

**Comment by PatilShreyas** [comment]
Thanks, @Awsom3D for this issue. This issue has been fixed in the new version `2.2.1`.

**Comment by PatilShreyas** [comment]
> <img src="https://user-images.githubusercontent.com/1741288/115840568-1eefbe80-a41c-11eb-8135-cfe54edd560e.jpg" height="300"/>

Also, @Awsom3D, as I can see you've included the privacy police link in the message. The good news is that now you can make it clickable 🎉.

With `v2.2.1` now you can add HTML spanned text for the message.

**Comment by Awsom3D** [comment]
Thank you so much @PatilShreyas ; this is awesome 😍

**Comment by Awsom3D** [comment]
@PatilShreyas Just so you know, since you switched to HTML, the \n are not processed and the modal text.

I'll just use <br> for now, but other developers could be confused or see it as a regression.

![Screenshot_20210424-181807](https://user-images.githubusercontent.com/1741288/115965433-8d6e7280-a529-11eb-8331-14fc1cb7af00.jpg)

**Comment by PatilShreyas** [comment]
Ok @Awsom3D

**Comment by Awsom3D** [comment]
If we could have an access to the Textview, maybe we could use [`Linkify`](https://developer.android.com/reference/kotlin/android/text/util/Linkify) without using HTML.

`Linkify.addLinks(textview, Linkify.WEB_URLS)`

**Comment by Awsom3D** [comment]
IMO using the html markup `<br>` is an hotfix, because if you want the MaterialDialog to be easy to use for users switching from classic AlertDialog, you can't ask them to change all of their translations, and use another language (even if HTML is pretty simple) to make it work.

Maybe keep the way things were before and add an `dialog.enableHtml(boolean)`  ?

**Comment by PatilShreyas** [comment]
Actually support for HTML is not only to show links. Developers can customise message styling as they want. But whatever you mentioned above makes sense. So I think, instead of directly getting input from `Builder`, we can have another builder method specific for spanned text like `.setMessage(Spanned spannedText)` which will be more generic and specific for HTML formatting.
