### ISSUE TITLE
Generic Message support: Support for separate plain text and Spanned text

### ISSUE THREAD

**Issue by PatilShreyas** [PatilShreyas/MaterialDialog-Android#49]
IMO using the html markup `<br>` is an hotfix, because if you want the MaterialDialog to be easy to use for users switching from classic AlertDialog, you can't ask them to change all of their translations, and use another language (even if HTML is pretty simple) to make it work.

Maybe keep the way things were before and add an `dialog.enableHtml(boolean)`  ?

_Originally posted by @Awsom3D in https://github.com/PatilShreyas/MaterialDialog-Android/issues/44#issuecomment-826120127_

**Comment by PatilShreyas** [comment]
https://github.com/PatilShreyas/MaterialDialog-Android/issues/44#issuecomment-826223391

**Comment by PatilShreyas** [comment]
@Awsom3D this is also fixed. Now it's more generic and control is in the hand of the developer and now, the library is not formatting text internally. 

Example:

```java
.setMessage("Lorem Ipsum") // This will set plain text message
.setMessage(Html.fromHtml("<b>Lorem Ipsum</b>")) // This will set spanned text message
```

Thank you for having a discussion on this and helping this library to make it better!

**Comment by Awsom3D** [comment]
@PatilShreyas many thanks ! I'm glad I could help.
