### ISSUE TITLE
[BUG] Button alignment with multi-line-text

### ISSUE THREAD

**Issue by jatsqi** [PatilShreyas/MaterialDialog-Android#51]
**Version**: 2.2.2
**API-Level**: 30 
**Problem**: If only one of the two buttons (positive, negative) has a multi-line-text, then this button is no longer aligned with the other one.
Screenshot: 
![See here](https://user-images.githubusercontent.com/54998646/116719826-ce5c0080-a9db-11eb-9539-00923c3fa614.png)

Is this behavior intended or is there a configuration option somewhere that I missed?
I could eventually provide a PR for this if the fix is easy. :+1:

**Comment by PatilShreyas** [comment]
Thanks for filling this! This will definitely help to make this library
better.

You're always welcome for the contributions so you can raise a PR with
master as a base branch

**Comment by jatsqi** [comment]
Thank you for your answer!
How do you want the layout to behave?

![Option 1](https://user-images.githubusercontent.com/54998646/116786948-c1a1e000-aaa1-11eb-9e80-edbb98a1ce4e.png)
Both buttons are pushed to the top of the container.

![Option 2](https://user-images.githubusercontent.com/54998646/116786955-cbc3de80-aaa1-11eb-909c-f89424701d76.png)
Both buttons are centered. I think this is also consistent with the behavior in landscape mode, isn´t it?

If this question is resolved I can provide a PR for this pretty soon.

**Comment by PatilShreyas** [comment]
In my opinion, Option 2 looks good.

**Comment by PatilShreyas** [comment]
Re-opened issue since this fix is not yet released. Will close after release.

**Comment by PatilShreyas** [comment]
This has been released. Thanks for the contribution @jatsqi 😃
