### ISSUE TITLE
[FEATURE REQUEST] How to handle dark theme with dialog ?

### ISSUE THREAD

**Issue by paktech1** [PatilShreyas/MaterialDialog-Android#55]
Write information about Bug/Feature Request here
When daylight theme is enabled the button and text color both become black. how can I set the dialog theme?

**Comment by PatilShreyas** [comment]
Refer to this section in the docs: https://github.com/PatilShreyas/MaterialDialog-Android#iii-customize-dialog-theme-optional

You can override the theme in your `style.xml` for different UI modes
