### ISSUE TITLE
[HELP/FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Shemmy3** [PatilShreyas/MaterialDialog-Android#56]
I'm trying to create a dialog with a `numberPicker` normally i would use the dialog builder and inflate a layout then pass it to the builder using the `setView` method but after reading the source of this library I don't see any method for this neither a method for using the android dialog builders singlechoice list and multiple choice list dialog methods

Basically
Is there anyone way to set a custom view, single choice and multiple choice list dialog?
Thanks.

**Comment by PatilShreyas** [comment]
There's no way to set custom view here. The purpose of this library is to show title, text and animation only.
